### ISSUE TITLE
Thali detail search on Telegram

### ISSUE THREAD

**Issue by mustafamnr** [taha2009/faiz-static#132] opened 2016-02-20 09:37 UTC

**Comment by murtraja** [comment] 2016-08-27 09:14
please inform me what calls should correspond to what data?
e.g.
/tn 23
should display what details for thali 23

and what all commands should my bot support?

do you want to have some authentication or anyone with telegram can access this sensitive information?

**Comment by murtraja** [comment] 2016-08-29 13:16
please see the legends at the bottom first

**work done so far:**

1) bot @ PA <==> db @ SG
 initially @murtaza52 introduced me to telegram bots and provided me a demo google sheet link in which thali details were stored. my job was to read from the cloud and based on the query retrieve the particular information.

1's implementation) used a free service by PA by setting a webhook at this domain for the bot, whenever a request was fired from telegram by the user, this bot crawled through the sheet and got the relevant information back to the user

2) user <=/=> bot @ FS
we then shifted to MySQL and the sheets idea was altogether dropped and the bot was rendered useless - the new job was to set the webhook at hostinger so that when user fires a request, it should go to FS and the relevant information would be request from database and then furnished to the user who asked for it

2's limitations) i learnt that webhook can only be set for those domains who support SSL or HTTPS. since hostinger doesn't support it (actually it does support in the paid account), this implementation was dropped.

3) user <==> bot @ PA <=/=> db @ FS
then it occurred to me that why not host the bot on PA where HTTPS support is built in, and use it to communicate between the user and the database located at faizstudents.com. of course it will be slow because two web servers are involved but just by fraction of seconds.

3's limitations) pythonanywhere.com does not support communication between those sites who don't have public api i.e. only some whitelisted sites can be accessed through it. so essentially i could not query the database from pythonanywhere.com to faizstudents.com due to this.

4) user <==> telegram server <========> bot,db @ FS
instead of having a webhook, telegram also supports a manual method to get the user's request, but the problem is that we need to constantly check for it as opposed to the previous method where you are automatically informed.

4's limitations) hostinger does not support a cron job on minute basis, it supports a larger time interval like hours or days. So if a user was to fire a request, on the worst case it would take an hour or so to process the request and get the reply, rendering the whole idea of "fast response" useless.

5) user <==> bot @ PA <==> db @ SG <========= db @ FS
then another idea popped up which has close ties with  #162 . why not take the database backup using google sheets and then use it for telegram bot database (now pythonanywhere.com will be able to access the data through sheets because it has public API, refer 3rd point above) essentially killing two birds with one stone

5's limitations) @yusuf4u52 suggested that backing up data on google sheets is a very inconvenient approach since in order to actually use that backup, SQL queries will have to be built first. the second reason is that this data will be a day old (assuming taking backup every day, we can take it every hour but the point remains), so now this time the accuracy of the data is compromised

6) user <==> bot @ herokuapp.com <==> db @ FS
Mufaddal bhai Jamal recommended Heroku wherein https support was built in. i tried that and it worked since heroku apps are allowed to communicate with other servers - no such system as whitelisted sites. so currently i am using this approach to solve the problem

**legends**
PA = pythonanywhere.com
FS = faizstudents.com
SG = sheets.google.com
<==>  connection possible
<=/=> connection not possible
<=======> slow or repeated update
@ located at domain

**Comment by murtraja** [comment] 2022-05-09 18:51
This is fixed

![image](https://user-images.githubusercontent.com/7806954/167477365-a5a54029-8be7-46d8-beb9-69e6b2921acc.png)


![image](https://user-images.githubusercontent.com/7806954/167477427-ef953872-ba64-4d51-bde8-963ae3078388.png)

**Comment by murtraja** [comment] 2022-05-09 18:51
@mustafamnr Please close this issue

**Comment by mustafamnr** [comment] 2022-05-14 05:25
Its looks good.

**Closed** 2022-05-14 05:25 UTC
